# Pipeline parameters

#Fasta with the reference.
reference_file: "/path/to/ref.fasta"

#Reference name.
reference_name: "Ref"

#Sequencing platform for picard
platform: "illumina|solid|etc"

#Quality for depth assesment
quality: 30

#Parameters for plot making. SIZE is the window size, STEP is the step size
size: 1000
step: 1000

#Samples to align
samples:
  - Sample1
  - Sample2
